export let myColors = {
    pastelOne: "#BCCEF8",
    pastelTwo: "#D2DAFF",
    pastelThree: "#FFB3B3",
    pastelFour: "#C9F4AA",
    pastelFive: "#BCCEF8",
    pastelSix: "#FCC2FC",
    pastelSeven: "#8DCEB8",
    piLightBlue: "#0984e3",
    darkBlueButtonBGColor: "#1948AA",
    navbarIconColor: "#64688D",
    infoColor: '#4F588A',
    secondColor: "#8DCEB8",
    notificationBadgeColor: "#FF3B30",
};
